plugins:
  follow_show_statistics_on_profile:
    default: true
    client: true
  follow_follower_notifications_enabled:
    default: true
    client: true
  discourse_follow_enabled:
    default: true
    client: true
